name: Testing

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Check formulae
        run: brew test-bot --only-tap-syntax

  build:
    needs: check
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - macos-13
          - macos-14
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - run: brew test-bot --only-tap-syntax
      - run: brew test-bot --only-formulae
      - name: Upload bottles as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bottles-${{ matrix.runner }}
          path: "*.bottle.*"
