name: Testing

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Check formulae
        run: brew test-bot --only-tap-syntax

  build:
    if: github.event_name == 'pull_request'
    needs: check
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Build bottles
        run: |
          brew test-bot --only-cleanup-before
          brew test-bot --only-formulae --skip-recursive-dependents
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: '*.bottle.*'
