name: Testing

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Check formulae
        run: brew test-bot --only-tap-syntax

  build:
    if: github.event_name == 'pull_request'
    needs: check
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      # - name: Set up Homebrew
      #   uses: Homebrew/actions/setup-homebrew@master
      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - run: brew test-bot --only-tap-syntax
      - run: brew test-bot --only-formulae --skip-recursive-dependents
        if: github.event_name == 'pull_request'
      - name: Uplod bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: '*.bottle.*'
